kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: bakaziki

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
        - name: backend
          image: riya2612/bakaziki-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          