kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: bakaziki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:

      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101

      containers:
        - name: frontend
          image: riya2612/bakaziki-frontend:${GITHUB_SHA}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run

      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}